### ISSUE TITLE
Improve motion detection

### ISSUE THREAD

**Issue by FutureSharks** [FutureSharks/rpi-security#27]
There are too many false alarms due to (I think) light changes.

**Comment by qlerebours** [comment]
I also experienced those false alarms. It seems logic that this is due to light changes, I read topics on internet and maybe found a solution here: https://medium.com/@citrusbyte/motion-detection-with-raspberry-pi-e46f4e3cd9a6

If I understood correctly, this is a solution that is simple to implement: Just use a "isFirstTrigger" variable to check wether this is the first time that motion has been detected in a row. If its the case, the motion detection will be ignored (in case of light change it shouldn't trigger a second time). If this is the second time, then an alert is emited.

I tried to implement this fix on another branch, i will test it soon. In the article, it's advised to use 1 second between each motion detection check, I believe that this is more in the rpi security project.

What do you think about this kind of fix ? FYI, I didn't find better motion detection algorithm with Raspberry Motion Detection library

**Comment by FutureSharks** [comment]
Hey @qlerebours,
Sounds like a good idea, I would be very happy if it works!

I tried a few different things, like fixing the camera settings, disabling auto and sleeping some time and various other ideas to stop the false alarms. None of it really worked well and now the  `RpisCamera` class is quite complicated.

Please test your idea and make a PR if it works!

**Comment by qlerebours** [comment]
Hello @FutureSharks 
The solution I wanted to use didn't work, that's why I worked a lot to test different other algorithms like human detection, face detection, motion detection etc ...
I finally found a solution that seems to be working pretty well. It's a motion detection that uses OpenCV. I integrated the algorithm to the rpi-security, i'm currently testing and I think I will test during a week to be sure there isn't any issue.

**Comment by FutureSharks** [comment]
OK interesting. I look forward to see how it goes!

Previously I didn't bother with openCV the installation process is such a pain. You need compile it from source so it made the whole installation process for `rpi-security` much more complicated.

Is it any easier now? Can it be installed with pip?

**Comment by qlerebours** [comment]
Yeah this is much easier now, you can run `sudo pip3 install opencv-python` to install it.
I'll remember to update the README.md before submitting the PR

**Comment by FutureSharks** [comment]
OK nice.

Also need to update here: https://github.com/FutureSharks/rpi-security/blob/master/setup.py#L22

**Comment by xychix** [comment]
Did this change happen? Item seems open.

After looking for security solutions I'm now considering this as none of the commercial products suited my needs.

**Comment by FutureSharks** [comment]
It did not happen.

I tried a few ideas but couldn't stop false positives when using motion detection from the camera. I then reverted back to version 0.7.

I don't really have time to look at it these days. Pull requests welcome though :)

**Comment by qlerebours** [comment]
I'm sorry I had a lot of things to do that prevented me to check the last things I had to check before submitting the PR. I will do that this weekend !

**Comment by qlerebours** [comment]
I could test during the previous week and I didn't have false alarms ! :+1: 
I will submit a PR but I really advise you to test because the code structure changed (Obviously i kept the same files and threads, but the loop you were doing in `monitor_alarm_state` thread has changed. I will explain that in the PR

**Comment by FutureSharks** [comment]
Now resolved https://github.com/FutureSharks/rpi-security/pull/35
